name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run unite tests with Gradle
      run: ./gradlew test --stacktrace
    - name: Build with Gradle
      run: ./gradlew build --stacktrace
    - name: Upload debug APK
      uses: actions/upload-artifact@v1
      with:
        name: karuna-debug-app
        path: app/build/outputs/apk/debug/app-debug.apk
    - name: Upload release APK
      uses: actions/upload-artifact@v1
      with:
        name: karuna-release-app
        path: app/build/outputs/apk/release/app-release-unsigned.apk
